package com.github.leomartins1999.aoc.day8

import kotlin.test.Test
import kotlin.test.assertEquals

class Day8Test {
    private val input =
        """
        ............
        ........0...
        .....0......
        .......0....
        ....0.......
        ......A.....
        ............
        ............
        ........A...
        .........A..
        ............
        ............
        """.trimIndent()

    @Test
    fun part1Example() {
        assertEquals(14, Day8(input).part1())
    }

    @Test
    fun part2Example() {
        assertEquals(34, Day8(input).part2())
    }

    @Test
    fun part2Example2() {
        val input =
            """
            T.........
            ...T......
            .T........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            ..........
            """.trimIndent()

        assertEquals(9, Day8(input).part2())
    }
}
