/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.leomartins1999

import java.io.File

private const val BASE_PACKAGE = "com.github.leomartins1999"

fun main() {
    runDay(1)
    runDay(2)
    runDay(3)
    runDay(4)
    runDay(5)
    runDay(6)
    runDay(7)
    runDay(8)
}

private fun runDay(number: Int) {
    val day = Class.forName("$BASE_PACKAGE.day$number.Day$number")
        .constructors
        .first()
        .newInstance() as Day

    val input = getFileText("./input/day-$number.txt")

    val part1 = day.part1(input)
    val part2 = day.part2(input)

    println("##### Day $number ######")
    println("Day $number (Part 1): $part1")
    println("Day $number (Part 2): $part2")
}

private fun getFileText(path: String) = File(path).readText()
