name: AoC 2022

on:
  pull_request:
    paths:
      - ./aoc-2022/**

jobs:
  aoc-2022:
    name: AoC 2022
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./aoc-2022
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
      - name: Run KTLint
        run: ./gradlew ktlintCheck
      - name: Run tests
        run: ./gradlew test -i
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "**/build/test-results/test/*.xml"
